import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import type { ReactNode } from 'react';
import type { Locale } from '@/i18n-config';
import { Header } from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  params: { lang: Locale };
}

export default function ({ children, params: { lang } }: RootLayoutProps) {
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Header lang={lang} />
        {children}
      </body>
    </html>
  );
}
